require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/update'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'vendor/bundle/**/*'
    - 'public/**/*'
    - 'tmp/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/routes.rb'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'app/helpers/application_helper.rb'

Naming/VariableName:
  EnforcedStyle: snake_case
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: false

Style/BlockDelimiters:
  FunctionalMethods:
    - let
    - let!
    - subject
  Exclude:
      - "spec/**/*_spec.rb"

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
