version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: 'db'
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp:delegated
volumes:
  pgdata:
